### ISSUE TITLE
ksml gives a java.lang.IllegalArgumentException: Illegal base64 character 7b    running against the Axual trial env

### ISSUE THREAD

**Issue by frochse** [Axual/ksml#32]
I build the KSML container to run against a Axual environment. I tried to run it against my current trail environment and a working stream. I used on of the examples which just prints the message (the demo inspect ksml). After a start the container with the working config it start but eventually it fails with the following exception 

```
docker run --name ksml-example --rm -ti -v /Users/frenkochse/src/ksml/examples:/ksml -w /ksml axual/ksml:latest

2022-04-07T09:09:04,524Z [system] [pool-1-thread-1] ERROR io.axual.common.tools.SslUtil -
                Key with alias "dst.root.ca.x3.cert.pem": CN=DST Root CA X3, O=Digital Signature Trust Co. became invalid at Thu Sep 30 14:01:15 UTC 2021
2022-04-07T09:09:04,946Z [system] [pool-1-thread-1] INFO  io.axual.ksml.user.UserFunction -
                Registered function 'ksml_pipelines_main_forEach(key:?, value:?)'
2022-04-07T09:09:11,035Z [system] [pool-1-thread-1] INFO  i.a.k.g.TopologyGeneratorImpl -
                Activating Kafka Streams topology:
2022-04-07T09:09:11,035Z [system] [pool-1-thread-1] INFO  i.a.k.g.TopologyGeneratorImpl -
                KStream[key=BINARY:String, value=AVRO:io.axual.client.example.schema.Application]
2022-04-07T09:09:11,047Z [system] [pool-1-thread-1] INFO  i.a.k.g.TopologyGeneratorImpl -
                    ==> for_each_001 operation ForEach
2022-04-07T09:09:11,068Z [system] [pool-1-thread-1] INFO  i.a.k.g.TopologyGeneratorImpl -
 
...
...
...

Topologies:
   Sub-topology: 0
    Source: application_source (topics: [applicationlogevents])
      --> for_each_001
    Processor: for_each_001 (stores: [])
      --> none
      <-- application_source


2022-04-07T09:49:46,339Z [system] [streams-loganalyser-1-StreamThread-1] ERROR i.a.k.r.backend.axual.AxualBackend -
                Caught serious exception in thread!
java.lang.IllegalArgumentException: Illegal base64 character 7b
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
        at org.apache.kafka.streams.processor.internals.StreamTask.decodeTimestamp(StreamTask.java:1097)
        at org.apache.kafka.streams.processor.internals.StreamTask.initializeTaskTime(StreamTask.java:906)
        at org.apache.kafka.streams.processor.internals.StreamTask.resetOffsetsIfNeededAndInitializeMetadata(StreamTask.java:882)
        at org.apache.kafka.streams.processor.internals.StreamTask.completeRestoration(StreamTask.java:244)
        at org.apache.kafka.streams.processor.internals.TaskManager.tryToCompleteRestoration(TaskManager.java:461)
        at org.apache.kafka.streams.processor.internals.StreamThread.initializeAndRestorePhase(StreamThread.java:849)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:731)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:583)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:556)
```

I got some feedback which was pointing to the fact that the kafka registry is not able to proces the meta ?

**Comment by tonvanbart** [comment]
Hi Frenk, what catches my eye are these lines at the top of the log:
```
2022-04-07T09:09:04,524Z [system] [pool-1-thread-1] ERROR io.axual.common.tools.SslUtil -
                Key with alias "dst.root.ca.x3.cert.pem": CN=DST Root CA X3, O=Digital Signature Trust Co. became invalid at Thu Sep 30 14:01:15 UTC 2021
```
Do you still get this message? I would have to hunt down where this cert is coming from and who (if anyone...) should update it.

**Comment by jeroenvandisseldorp** [comment]
This issue was implicitly resolved a while ago, so closing this issue.
