### ISSUE TITLE
Running 09-demo-aggregate.yaml using script results in Linux ownership issues

### ISSUE THREAD

**Issue by tonvanbart** [Axual/ksml#36]
Found this while trying to reproduce #35 on my private (Linux) laptop - fails with yet another exception:

Platform: Ubuntu 20.04 LTS
Steps

- build ksml runner image: `docker build -t axual/ksml -f Dockerfile-build-runner . --build-arg runner=ksml-runner`
- start local environment: `docker-compose up -d`
- modify examples/ksml-runner.yml so that it points to 09-demo-aggregate.yaml
- start the local run: `./examples/run.sh`

Expected result: same exception as #35 
Actual result: the runner fails with the following stacktrace:
```
2022-04-22T20:55:17,973Z [system] [main] INFO  i.a.k.g.TopologyGeneratorImpl -
                  owner_count: retention=PT3M, key=BINARY:String, value=BINARY:Long, caching=false
Exception in thread "main" org.apache.kafka.streams.errors.StreamsException: org.apache.kafka.streams.errors.ProcessorStateException: state directory [/ksml/io.ksml.example.processor] doesn't exist and couldn't be created
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:807)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:782)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:692)
	at io.axual.ksml.runner.backend.kafka.KafkaBackend.<init>(KafkaBackend.java:82)
	at io.axual.ksml.runner.backend.kafka.KafkaBackendProvider.create(KafkaBackendProvider.java:44)
	at io.axual.ksml.runner.config.KSMLRunnerConfig.getConfiguredBackend(KSMLRunnerConfig.java:80)
	at io.axual.ksml.runner.KSMLRunner.main(KSMLRunner.java:57)
Caused by: org.apache.kafka.streams.errors.ProcessorStateException: state directory [/ksml/io.ksml.example.processor] doesn't exist and couldn't be created
	at org.apache.kafka.streams.processor.internals.StateDirectory.<init>(StateDirectory.java:134)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:804)
	... 6 more
.../ksml on  main [$!?] 

```

**Comment by tonvanbart** [comment]
Tried to work around by trying to create this directory by hand in the project root (and giving it chmod 777), but got the same result.

**Comment by jeroenvandisseldorp** [comment]
You should probably point to a user directory somewhere, potentially relative to the working directory. If you leave out the initial '/' then Kafka Streams creates a cache directory underneath the directory where you run.

**Comment by tonvanbart** [comment]
I tried changing the value from `/ksml` to `ksml` in `ksml-runner.yml` (so, leaving out the initial `/`, however this does not work:
```
Exception in thread "main" io.axual.ksml.runner.exception.KSMLRunnerConfigurationException: The provided path does not exists or is not a directory
Configuration Key   : 'workingDirectory'
Configuration Value : 'ksml' 
        at io.axual.ksml.runner.config.KSMLConfig.validate(KSMLConfig.java:75)
        at io.axual.ksml.runner.config.KSMLRunnerConfig.validate(KSMLRunnerConfig.java:51)
        at io.axual.ksml.runner.KSMLRunner.main(KSMLRunner.java:55)

```
Is that the correct property to change?

**Comment by tonvanbart** [comment]
Looking in `run.sh` I see that the runner image is started like this;
```
docker run --name ksml-example --rm -ti -v "${BASEDIR}":/ksml -w /ksml --network ksml_example axual/ksml:latest
```
So it's mounting the directory where `run.sh` resides as `/ksml` in the container and then sets that as the working directory. `ksml-runner.yml` is pointing to that. The process inside the image is running as USER 1024 but this is not present on the host, I think that that is the cause of the ownership issue.
