### ISSUE TITLE
Example 10-demo-queryabletable is missing a topic

### ISSUE THREAD

**Issue by tonvanbart** [Axual/ksml#41]
Upon building the runner image and running `10-demo-queryabletable` as per the instructions in the README, the run fails with the following stacktrace:

```
2022-05-13T15:35:20,452Z [system] [io.ksml.example.processor-eccaa6cf-4139-49ea-ad4b-33ba260763c3-StreamThread-1] ERROR o.a.k.c.c.i.ConsumerCoordinator -
                [Consumer clientId=io.ksml.example.processor-eccaa6cf-4139-49ea-ad4b-33ba260763c3-StreamThread-1-consumer, groupId=io.ksml.example.processor] User provided listener org.apache.kafka.streams.processor.internals.StreamsRebalanceListener failed on invocation of onPartitionsAssigned for partitions []
org.apache.kafka.streams.errors.MissingSourceTopicException: One or more source topics were missing during rebalance
	at org.apache.kafka.streams.processor.internals.StreamsRebalanceListener.onPartitionsAssigned(StreamsRebalanceListener.java:58)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.invokePartitionsAssigned(ConsumerCoordinator.java:293)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:430)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:449)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:365)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:508)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1261)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1230)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:925)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollPhase(StreamThread.java:885)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:720)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:583)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:556)
2022-05-13T15:35:20,455Z [system] [io.ksml.example.processor-eccaa6cf-4139-49ea-ad4b-33ba260763c3-StreamThread-1] ERROR o.apache.kafka.streams.KafkaStreams -
                stream-client [io.ksml.example.processor-eccaa6cf-4139-49ea-ad4b-33ba260763c3] Encountered the following exception during processing and the registered exception handler opted to SHUTDOWN_CLIENT. The streams client is going to shut down now.
```
Looking in the yaml file, I suspect that topic `ksml_sensordata_table` is missing.

**Comment by tonvanbart** [comment]
I tried to add creation of the table topic in the `kafka-seup` container in `docker-compose.yml` (which creates all the topic when the compose starts up), however the same stacktrace occurs.

**Comment by tonvanbart** [comment]
After having all images rebuilt when doing `docker compose up`, the offending example also works. Apparently it was still using an old version of the `kafka-setup` container somehow and the table was not created (?)
Will create a PR.
